apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: navatech-app
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream backend {
        server 127.0.0.1:8080;
      }
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }
        location /health {
          access_log off;
          return 200 "healthy\n";
          add_header Content-Type text/plain;
        }
      }
    } 