apiVersion: v1
kind: Service
metadata:
  name: navatech-app-service
  namespace: navatech-app
  labels:
    app: navatech-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: navatech-app 